const image = {
    scr1: require("../assets/images/1stscrn.png"),
    scr2: require("../assets/images/2ndscrn.png"),
    dealpic: require("../assets/images/dealpic.png"),
    success: require("../assets/images/success.png"),
    planeimg: require("../assets/images/planeimg.png"),
    hotelimg: require("../assets/images/hotelimg.png"),
    privacy: require("../assets/images/privacy.png"),
    priceBar: require("../assets/images/priceBar.png"),
    map: require("../assets/images/map.png"),
    image1: require("../assets/images/image1.png"),
    image2: require("../assets/images/image2.png"),
    image3: require("../assets/images/image3.png"),
    image4: require("../assets/images/image4.png"),
    image5: require("../assets/images/image5.png"),
    image6: require("../assets/images/image6.png"),
    image7: require("../assets/images/image7.png"),
    ramada: require("../assets/images/ramada.png"),
    gal1: require("../assets/images/gal1.png"),
    gal2: require("../assets/images/gal2.png"),
    gal3: require("../assets/images/gal3.png"),
    gal4: require("../assets/images/gal4.png"),
    gal5: require("../assets/images/gal5.png"),
    gal6: require("../assets/images/gal6.png"),
    gal7: require("../assets/images/gal7.png"),
    gal8: require("../assets/images/gal8.png"),
    gal9: require("../assets/images/gal9.png"),
    gal10: require("../assets/images/gal10.png"),
    gal11: require("../assets/images/gal11.png"),
    gal12: require("../assets/images/gal12.png"),
    si1: require("../assets/images/si1.png"),
    si2: require("../assets/images/si2.png"),
    si3: require("../assets/images/si3.png"),
    bi1: require("../assets/images/bi1.png"),
    car1: require("../assets/images/car1.png"),
    car2: require("../assets/images/car2.png"),
    car3: require("../assets/images/car3.png"),
    car4: require("../assets/images/car4.png"),
    alamo: require("../assets/images/alamo.png"),
};

module.exports = image;